//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvendMpesaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int Id { get; set; }
        public string AuditKey { get; set; }
        public string ModuleName { get; set; }
        public string UserName { get; set; }
        public string Action { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public string RemoteIP { get; set; }
    }
}
