//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvendMpesaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoAuth
    {
        public long Id { get; set; }
        public string ClientHost { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string FullNames { get; set; }
        public Nullable<System.DateTime> AuthArrivalTime { get; set; }
        public Nullable<bool> IsConsumed { get; set; }
        public Nullable<bool> IsPolled { get; set; }
        public string Msisdn { get; set; }
    }
}
