//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvendMpesaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string DbIP { get; set; }
        public string DbPort { get; set; }
        public string DbUser { get; set; }
        public string DbPassword { get; set; }
        public string ConfirmC2b_Url { get; set; }
        public string ShortCode { get; set; }
    }
}
