//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvendMpesaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPESA_C2B_IMPORT
    {
        public int TID { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<System.DateTime> CompletionTime { get; set; }
        public Nullable<System.DateTime> InitiationTime { get; set; }
        public string Details { get; set; }
        public string TransactionStatus { get; set; }
        public Nullable<decimal> PaidIn { get; set; }
        public Nullable<decimal> WithDrawn { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string BalanceConfirmed { get; set; }
        public string ReasonType { get; set; }
        public string OtherPartyInfo { get; set; }
        public string Maker { get; set; }
        public string Checker { get; set; }
        public Nullable<System.DateTime> UploadTime { get; set; }
        public Nullable<bool> Verified { get; set; }
        public Nullable<bool> Reconciled { get; set; }
    }
}
