//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvendMpesaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPESA_C2B_ARCH_EXP
    {
        public int ID { get; set; }
        public string TransactionType { get; set; }
        public string TransID { get; set; }
        public string TransTime { get; set; }
        public Nullable<decimal> TransAmount { get; set; }
        public string BusinessShortCode { get; set; }
        public string BillRefNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<decimal> OrgAccountBalance { get; set; }
        public string ThirdPartyTransID { get; set; }
        public string MSISDN { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string MSG { get; set; }
        public Nullable<System.DateTime> MessageArrivalTime { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string PostedBy { get; set; }
        public string Status { get; set; }
        public string TillId { get; set; }
    }
}
