//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvendMpesaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPESA_C2B_REVERSAL
    {
        public int ID { get; set; }
        public string TransID { get; set; }
        public string ReversalID { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<decimal> ReversalAmount { get; set; }
        public string MSG { get; set; }
        public Nullable<decimal> AccountBalance { get; set; }
        public Nullable<int> Status { get; set; }
        public string C2bMsg { get; set; }
    }
}
