//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvendMpesaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT
    {
        public int ID { get; set; }
        public string ReportName { get; set; }
        public string ReportDescription { get; set; }
        public string BranchId { get; set; }
        public string ReportType { get; set; }
    }
}
